theme: jekyll-theme-slate
title: [Group Reading 2020, School of Informatics, Computing and Cyber Systems, Northern Arizona University]
description: [A short description of your site's purpose]
show_downloads: ["true" or "false" to indicate whether to provide a download URL]
google_analytics: [Your Google Analytics tracking ID]
